import {
  Loader2,
  User,
  Settings,
  Home,
  Building,
  Wrench,
  Calendar,
  BarChart3,
  FileText,
  Shield,
  Plus,
  Search,
  Camera,
  MapPin,
  AlertTriangle,
  CheckCircle,
  Clock,
  Menu,
  X,
  LogOut,
  Bell,
  ChevronDown,
  ChevronRight,
  Edit,
  Trash2,
  Download,
  Filter,
  MoreHorizontal,
  QrCode,
  Smartphone,
  Monitor,
  Wifi,
  WifiOff,
  RefreshCw,
  ArrowLeft,
  HelpCircle,
  Package,
  Printer,
  Scan
} from "lucide-react"

export const Icons = {
  spinner: Loader2,
  user: User,
  settings: Settings,
  home: Home,
  building: Building,
  wrench: Wrench,
  calendar: Calendar,
  barChart: BarChart3,
  barChart3: BarChart3,
  fileText: FileText,
  shield: Shield,
  plus: Plus,
  search: Search,
  camera: Camera,
  mapPin: MapPin,
  alertTriangle: AlertTriangle,
  checkCircle: CheckCircle,
  clock: Clock,
  menu: Menu,
  close: X,
  logOut: LogOut,
  bell: Bell,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  edit: Edit,
  trash: Trash2,
  download: Download,
  filter: Filter,
  moreHorizontal: MoreHorizontal,
  qrCode: QrCode,
  smartphone: Smartphone,
  monitor: Monitor,
  wifi: Wifi,
  wifiOff: WifiOff,
  refreshCw: RefreshCw,
  arrowLeft: ArrowLeft,
  helpCircle: HelpCircle,
  package: Package,
  printer: Printer,
  scan: Scan
}